BufeteBundle\Entity\Civiles:
    type: entity
    table: civiles
    indexes:
        IX_Relationship22:
            columns:
                - Id_Caso
    id:
        idCivil:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Civil
            generator:
                strategy: IDENTITY
    fields:
        pretencion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    oneToOne:
        idCaso:
            targetEntity: Casos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: civiles
            joinColumns:
                Id_Caso:
                    referencedColumnName: Id_Caso
            orphanRemoval: false
    lifecycleCallbacks: {  }
