BufeteBundle\Entity\Tribunales:
    type: entity
    table: tribunales
    id:
        idTribunal:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Tribunal
            generator:
                strategy: IDENTITY
    fields:
        tribunal:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Tribunal
        estadoTribunal:
            type: boolean
            nullable: false
            column: Estado_Tribunal
    lifecycleCallbacks: {  }
