imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BufeteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
#COnfiuracion por defecto para knp paginator con la modification de la plantilla en bootstrap
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template
        filtration: 'KnpPaginatorBundle:Pagination:filtration.html.twig'  # filters template


#Configuracion de ELasticaBundle, para las busquedas en el sistema
#referirse a https://www.youtube.com/watch?v=DDOF62dvuGc&t=1057s para instrucciones de instalacion
#https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
# Elasticsearch
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        bufete:
            types:
                estadosciviles:
                    mappings:
                        estadocivil: ~
                        Estadoestadocivil: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idEstadocivil
                        driver: orm
                        model: BufeteBundle\Entity\Estadosciviles
                        provider: ~
                        listener: ~
                        finder: ~
                tipocaso:
                    mappings:
                        tipo: ~
                        estadoTipo: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idTipo
                        driver: orm
                        model: BufeteBundle\Entity\Tipocaso
                        provider: ~
                        listener: ~
                        finder: ~
                ciudad:
                    mappings:
                        postalCiudad: ~
                        ciudad: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idCiudad
                        driver: orm
                        model: BufeteBundle\Entity\Ciudad
                        provider: ~
                        listener: ~
                        finder: ~
                departamentos:
                    mappings:
                        departamento: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idDepartamento
                        driver: orm
                        model: BufeteBundle\Entity\Departamentos
                        provider: ~
                        listener: ~
                        finder: ~
                paises:
                    mappings:
                        pais: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idPais
                        driver: orm
                        model: BufeteBundle\Entity\Paises
                        provider: ~
                        listener: ~
                        finder: ~
                bufetes:
                    mappings:
                        nombreBufete: ~
                        telefono1Bufete: ~
                        telefono2: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idBufete
                        driver: orm
                        model: BufeteBundle\Entity\Bufetes
                        provider: ~
                        listener: ~
                        finder: ~
                trabajos:
                    mappings:
                        trabajo: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idTrabajo
                        driver: orm
                        model: BufeteBundle\Entity\Trabajos
                        provider: ~
                        listener: ~
                        finder: ~
                tribunales:
                    mappings:
                        tribunal: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        identifier: idTribunal
                        driver: orm
                        model: BufeteBundle\Entity\Tribunales
                        provider: ~
                        listener: ~
                        finder: ~
