# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    vabadus_user_security.handler.login_success_handler.class: BufeteBundle\Service\LoginSuccessHandler
#    login_success_handler: BufeteBundle\Service\LoginSuccessHandler
#    parameter_name: value

services:
    app.autocont:
        class: BufeteBundle\Services\Autocont
        arguments: ["null"]

    app.registrocunoc:
        class: BufeteBundle\Services\Registrocunoc
        arguments: ['carne']
      
#    login_success_handler:
#        class: BufeteBundle\Services\LoginSuccessHandler
#        arguments: ["@router", "@security.context"]
#        tags:
#            - { name: 'monolog.logger', channel: 'security' }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
