practicas_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Practicas:index" }
    methods:  GET

practicas_show:
    path:     /{idPractica}/show
    defaults: { _controller: "BufeteBundle:Practicas:show" }
    methods:  GET

practicas_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Practicas:new" }
    methods:  [GET, POST]

practicas_edit:
    path:     /{idPractica}/edit
    defaults: { _controller: "BufeteBundle:Practicas:edit" }
    methods:  [GET, POST]

practicas_delete:
    path:     /{idPractica}/delete
    defaults: { _controller: "BufeteBundle:Practicas:delete" }
    methods:  DELETE
